export const codes={
    11000:"User of same email already exists",
    16755:"Please enter valid shop coordinates",
    email:'Email must not be empty and must be a string and valid email',
    password:'Password must not be empty and must be a unique string value',
    country:"Country must be a valid string",
    age:"Age must be a valid number",
    shopDetails:"ShopDetails should be of type array and should contain details about your shops",
    shopName:"shopName Must not be empty and must be a string",
    phoneNo:"phoneNo Must be a string and not empty and should be a valid unique phone number",
    address:"address Must be a string and must not be empty",
    coordinates:"coordinates Must be a valid coordinate with unique x and y coordinates of the shop",
    oldPassword:"oldPassword must be a string and must not be empty",
    newPassword:"newPassword must be a string and must not be empty",
    confirmPassword:"confirmPassword must be a string and must not be empty",
}